const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({headless:true,channel:'chrome'});
  const page = await browser.newPage({viewport:{width:390,height:844},timezoneId:'Asia/Tokyo'});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(() => localStorage.setItem('sl_guide_version','1'));
  await page.goto(process.env.STUDYCOPI_TEST_URL || 'http://127.0.0.1:8765');
  await page.waitForSelector('.today-summary strong');
  await page.waitForFunction(() => typeof playTimerSound === 'function');
  await page.evaluate(() => {
    backupState = {lastAt: Date.now()-BACKUP_INTERVAL-1000,dirty:false,snoozeUntil:0}; persistBackupState(); showBackupReminder();
  });
  assert.equal(await page.locator('#backup-reminder').isVisible(),false);
  await page.evaluate(() => { save('sl_notif_settings',{timer:true}); showBackupReminder(); });
  assert.equal(await page.locator('#backup-reminder').isVisible(),false);
  await page.evaluate(() => { save('sl_schedules',[{id:'test',subjectId:'s1',datetime:'2026-10-04T17:00',duration:1,status:'pending'}]); });
  assert.equal(await page.locator('#backup-reminder').isVisible(),false,'do not interrupt current session');
  await page.reload();
  assert.equal(await page.locator('#backup-reminder').isVisible(),true,'show next opening after three days');
  await page.locator('#backup-reminder').getByText('あとで',{exact:true}).click();
  await page.reload(); assert.equal(await page.locator('#backup-reminder').isVisible(),false);
  await page.evaluate(() => { backupState.snoozeUntil=0; persistBackupState(); showBackupReminder(); });
  const download = page.waitForEvent('download');
  await page.locator('#backup-reminder').getByText('ファイルに保存',{exact:true}).click();
  const saved = await download;
  const backup = JSON.parse(fs.readFileSync(await saved.path(),'utf8'));
  assert.equal(backup.schedules.length,1); assert.equal(backup.web.sound.key,'bell');
  assert.equal(await page.locator('#backup-reminder').isVisible(),false);
  await page.evaluate(() => showBackupReminder(Date.now()+BACKUP_INTERVAL+1));
  assert.equal(await page.locator('#backup-reminder').isVisible(),false,'no reminder without new data');
  await page.evaluate(() => showView('settings'));
  await page.locator('#alarm-sound').selectOption('chime');
  await page.getByText('音を試聴',{exact:true}).click();
  await page.waitForFunction(() => soundPreview && soundPreview.currentTime > 0);
  assert.ok(await page.evaluate(()=>soundPreview && soundPreview.src.endsWith('/chime.wav')));
  await page.reload(); assert.equal(await page.locator('#alarm-sound').inputValue(),'chime');
  await page.evaluate(() => { notifSettings.timer = false; notifyTimerEnd('数学'); });
  await page.waitForFunction(() => timerAudio.currentTime > 0);
  assert.ok(await page.evaluate(() => timerAudio.src.endsWith('/chime.wav')));
  await page.evaluate(() => showView('settings'));
  await page.locator('#alarm-sound-enabled').uncheck();
  assert.ok(await page.evaluate(() => timerAudio.paused));
  await page.evaluate(() => showView('schedule'));
  await page.locator('#view-schedule').getByText('時間割',{exact:true}).click();
  assert.equal(await page.evaluate(()=>ttMode),'grid');
  assert.equal(await page.locator('#timetable-grid').isVisible(),true);
  assert.equal(await page.locator('#view-timetable [data-plan-mode=grid]').getAttribute('aria-current'),'page');
  for (const width of [320,390]) {
    await page.setViewportSize({width,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth > innerWidth+1),false);
  }
  const manifest = await (await page.request.get(new URL('manifest.json',page.url()).href)).json();
  const webIcon = await (await page.request.get(new URL(manifest.icons[0].src,page.url()).href)).body();
  assert.deepEqual(webIcon,fs.readFileSync(path.join(__dirname,'../android/app/src/main/res/drawable-nodpi/app_icon_art.png')));
  assert.deepEqual(errors,[]);
  await browser.close(); console.log('PASS: three-day dirty-only backup, snooze/export reset, sound persistence/preview, direct timetable and shared icon');
})().catch(error => { console.error(error); process.exit(1); });
