const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({headless:true,channel:'chrome'});
  const context = await browser.newContext({viewport:{width:320,height:740},timezoneId:'Asia/Tokyo'});
  const page = await context.newPage();
  const errors=[]; page.on('pageerror', e=>errors.push(e.message));
  await page.addInitScript(()=>localStorage.setItem('sl_guide_version','1'));
  await page.goto(process.env.STUDYCOPI_TEST_URL || 'http://127.0.0.1:8766');
  await page.waitForFunction(()=>typeof checkScheduledFocus==='function');
  await page.getByRole('button',{name:'その他',exact:true}).click();
  await page.getByRole('button',{name:/StudyCoPiについて/}).click();
  assert.equal(await page.locator('[data-app-version]').textContent(),'1.5.0');
  assert.ok(await page.getByText('ひろかわびーち（hirokawa-beach）',{exact:true}).isVisible());
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
  fs.mkdirSync('.artifacts/web',{recursive:true});
  await page.screenshot({path:'.artifacts/web/about-320.png',fullPage:true});
  await page.evaluate(()=>showView('settings'));
  assert.equal(await page.locator('#scheduled-focus-enabled').isChecked(),false);
  await page.evaluate(()=> {
    const now=new Date(); now.setMilliseconds(0);
    schedules=[{id:'due',subjectId:'s1',datetime:now.toISOString(),duration:1,status:'pending',content:'問題集 p.12'}];
    save('sl_schedules',schedules);
  });
  await page.locator('#scheduled-focus-enabled').check();
  await page.evaluate(()=>checkScheduledFocus());
  await page.locator('#scheduled-focus-dialog[open]').waitFor();
  assert.equal(await page.locator('#scheduled-focus-subject').textContent(),'数学');
  assert.equal(await page.locator('#focus-active').isVisible(),false,'opening does not start timer');
  assert.equal(await page.evaluate(()=>schedules[0].actualDuration),undefined,'opening does not record time');
  await page.screenshot({path:'.artifacts/web/scheduled-focus-320.png'});
  const second=await context.newPage();
  await second.goto(page.url()); await second.waitForFunction(()=>typeof checkScheduledFocus==='function');
  await second.evaluate(()=>checkScheduledFocus());
  assert.equal(await second.locator('#scheduled-focus-dialog').isVisible(),false,'other tabs share the claimed schedule');
  await second.close();
  page.once('dialog',d=>d.accept());
  await page.getByRole('button',{name:'今回は解除する',exact:true}).click();
  assert.equal(await page.locator('#scheduled-focus-dialog').isVisible(),false);
  await page.evaluate(()=>checkScheduledFocus());
  assert.equal(await page.locator('#scheduled-focus-dialog').isVisible(),false,'dismissed schedule is not repeated');
  await page.reload(); await page.waitForFunction(()=>typeof checkScheduledFocus==='function');
  assert.equal(await page.locator('#scheduled-focus-enabled').isChecked(),true);
  await page.evaluate(()=>checkScheduledFocus());
  assert.equal(await page.locator('#scheduled-focus-dialog').isVisible(),false,'reload does not replay');
  // Moved time is a different occurrence; completion/deletion or an active timer blocks it.
  await page.evaluate(()=>{ schedules[0].datetime=new Date(Date.now()-1000).toISOString(); schedules[0].status='done'; });
  await page.evaluate(()=>checkScheduledFocus()); assert.equal(await page.locator('#scheduled-focus-dialog').isVisible(),false);
  await page.evaluate(()=>{ schedules[0].status='pending'; });
  await page.evaluate(()=>checkScheduledFocus()); await page.locator('#scheduled-focus-dialog[open]').waitFor();
  await page.locator('#scheduled-focus-start').click();
  assert.equal(await page.locator('#focus-active').isVisible(),true);
  assert.equal(await page.locator('#scheduled-focus-dialog').isVisible(),false);
  assert.equal(await page.evaluate(()=>focusSchedId),'due');
  await page.evaluate(()=>{ schedules.push({...schedules[0],id:'another'}); });
  await page.evaluate(()=>checkScheduledFocus()); assert.equal(await page.locator('#scheduled-focus-dialog').isVisible(),false);
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('PASS: v1.5.0 about, opt-in waiting focus, no automatic timer/record, cross-tab and reload deduplication, manual timer start');
})().catch(e=>{console.error(e);process.exit(1);});
